language: java


jdk:
  - openjdk11
  
before_install:
  - sudo apt-get -y install xmlstarlet
 
script: 
  - gradle check
 
after_failure:
  - cat /home/travis/build/simonpoole/mapsplit/build/test-results/test/*.xml